version: "3.0"
services:
  db:
    container_name: cash_db
    image: mongo:4.4.3
    volumes:
    - ${MONGO_DATA_PATH:-./.data/}:/data/db

  api:
    env_file:
      - .env
    container_name: cash_api
    build:
      dockerfile: Dockerfile
      context: .
    image: cash_api
    command: uvicorn --host 0.0.0.0 --port 8080 --workers 1 src.server:api
    ports:
    - ${API_HOST:-0.0.0.0}:${API_PORT:-8080}:8080
